# Generated by Django 5.2.1 on 2025-05-20 22:19

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
            preserve_default=False,
        ),
    ]
