# Generated by Django 5.2.1 on 2025-05-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_updated_at_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the applicant', null=True),
        ),
    ]
